### ISSUE TITLE
Files without comments are purged

### ISSUE THREAD

**Issue by yvo-niedrich** [alexkohler/cfmt#3]
# Scenario
Create a file `test.go` with the following contents:
```go
package "test"

type Uncommented struct{}
```

Then run `cfmt -m 100 -w test.go`.

# Expected
File remains unchanged

# Reality
The file's contents are purged. (0 byte file)

**Comment by alexkohler** [comment]
```Go
file, err := os.Create(fileName)
if err != nil {
	log.Println(err)
	return
}
defer file.Close()

if len(f.Comments) == 0 {
	return
}
```

Thought I'd accounted for this - but it looks like the check happens after the file is purged rather than before. Good find! Thanks for submitting an issue :+1:
